import Navbar from 'components/navbar/navbar'
import Tab from 'components/tab/tab'
import Head from 'next/head'
import React from 'react'

type MainLayoutType = {
    children: React.ReactNode
}

function MainLayout({ children }: MainLayoutType) {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='min-h-screen bg-slate-100'>
                {children}
            </main>
            <div id="portal"></div>
        </>
    )
}

export default MainLayout

